#!/usr/bin/env bash

# Convenience script for checking constraints locally

set -euxo pipefail

cd `dirname $0`

MAJOR=23
LTS=$(curl -s https://www.stackage.org/download/snapshots.json | jq -r '.["lts"]')

echo "$LTS"

export GHCVER=$(sed -n "s/^ghc-version: \"\(.*\)\"/\1/p" "lts-$MAJOR-build-constraints.yaml")

curator update &&
  curator constraints --no-download --target=$LTS &&
  curator snapshot-incomplete --target=$LTS &&
  curator snapshot &&
  stack --resolver ghc-$GHCVER exec curator check-snapshot
