#!/bin/bash

# Convenience script for checking constraints locally

set -euxo pipefail

cd `dirname $0`

if [ $# -ne 2 ]; then
    echo "Usage: $0 MAJOR MINOR"
    exit 1
fi

MAJOR=$1
MINOR=$2
LTS="lts-$MAJOR.$MINOR"

echo "$LTS"

export GHCVER=$(sed -n "s/^ghc-version: \"\(.*\)\"/\1/p" "lts-$MAJOR-build-constraints.yaml")

curator update &&
  curator constraints --no-download --target=$LTS &&
  curator snapshot-incomplete --target=$LTS &&
  curator snapshot &&
  stack --resolver ghc-$GHCVER exec curator check-snapshot
